# Taskfile.yaml

version: '3'

vars:
  CLUSTER_NAME: zeus
  KIND_CONFIG: gitops/clusters/zeus/kind-config.yaml
  APP_OF_APPS: gitops/clusters/zeus/bootstrap/app-of-apps.yaml
  DEPENDENCIES:
    - docker
    - kind
    - kubectl
    - helm

  check-docker-running: &check-docker-running |
    docker info > /dev/null 2>&1

  check-cluster-running: &check-cluster-running |
    kind get clusters | grep -x {{.CLUSTER_NAME}}

tasks:
  default:
    aliases: [deploy, all, make]
    deps:
      - bootstrap

  bootstrap:
    desc: Create Kind cluster, bootstrap Argo CD, and apply app-of-apps
    deps:
      - create-cluster
      - deploy-argocd
      - deploy-app-of-apps
      - wait-core
      - get-argocd-password
      - deploy-custom-webservice

  check-dependencies:
    silent: true
    cmds:
      - |
        {{range .DEPENDENCIES}}
          if ! command -v {{.}} > /dev/null; then
            echo "{{.}} not found"
          fi
        {{end}}

  create-cluster:
    run: once
    preconditions:
      - *check-docker-running
    cmds:
      - kind create cluster --config={{.KIND_CONFIG}} --name {{.CLUSTER_NAME}}
    status:
      - *check-cluster-running

  clean-cluster:
    desc: Delete the Kind cluster
    cmds:
      - kind delete cluster --name {{.CLUSTER_NAME}}

  deploy-argocd:
    desc: Install Argo CD (bootstrap phase) with TLS terminated at Gateway
    run: once
    preconditions:
      - *check-cluster-running
    deps:
      - create-cluster
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo update
      - |
        helm upgrade --install argocd argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          --set server.insecure=true \
          --set configs.params.server\\.insecure=true \
          --set server.ingress.enabled=false \
          --set server.service.type=ClusterIP \
          --set notifications.enabled=false \
          --set dex.enabled=false
      - kubectl -n argocd wait deployment/argocd-server --for=condition=Available --timeout=300s

  clean-argocd:
    desc: Remove Argo CD namespace
    cmds:
      - kubectl delete ns argocd --ignore-not-found=true

  deploy-app-of-apps:
    desc: Apply app-of-apps so Argo CD reconciles the Zeus infra stack
    deps:
      - deploy-argocd
    cmds:
      - kubectl apply -f {{.APP_OF_APPS}}

  wait-core:
    desc: Wait for key platform components (Argo CD, Envoy Gateway, KubeVela, observability)
    deps:
      - deploy-app-of-apps
    cmds:
      - kubectl -n argocd wait deployment/argocd-server --for=condition=Available --timeout=300s
      - kubectl -n envoy-gateway-system wait deployment/envoy-gateway --for=condition=Available --timeout=300s
      - kubectl -n vela-system wait deployment/vela-core --for=condition=Available --timeout=600s
      - kubectl -n monitoring wait deployment/prometheus-grafana --for=condition=Available --timeout=600s
      - kubectl -n observability wait deployment/opentelemetry-operator-controller-manager --for=condition=Available --timeout=600s

  get-argocd-password:
    desc: Print Argo CD initial admin password
    deps:
      - deploy-argocd
    cmds:
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode; echo

  render-kubevela-addons:
    desc: Render KubeVela addon manifests into gitops/clusters/zeus/infra/50-kubevela-addons
    cmds:
      - vela addon enable velaux --dry-run > gitops/clusters/zeus/infra/50-kubevela-addons/velaux.yaml
      - vela addon enable fluxcd --dry-run > gitops/clusters/zeus/infra/50-kubevela-addons/fluxcd.yaml
  
  deploy-custom-webservice:
    desc: Deploy a sample custom webservice component to demonstrate KubeVela extensibility
    cmds:
      - kubectl -n vela-system apply -k kubevela-customization/CustomWebservices

  clean:
    aliases: [delete]
    deps:
      - clean-argocd
      - clean-cluster
