apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: golden-webservice
  namespace: vela-system
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        parameter: {
          image: string
          port: *8080 | int

          # Optional extra labels
          labels: *{} | [string]: string

          # Default probe path per your requirement
          probePath: *"/healthz" | string

          # Default resources (adjust to your org baseline)
          resources: *{
            requests: { cpu: "10m", memory: "80Mi" }
            limits:   { memory: "128Mi" }
          } | {...}

          # Optional envFrom configmap convention
          configMapName?: string
        }

        labels: {
          "app.oam.dev/component": context.name
        } & parameter.labels

        output: {
          apiVersion: "apps/v1"
          kind: "Deployment"
          metadata: {
            name: context.name
            labels: labels
          }
          spec: {
            selector: matchLabels: labels
            template: {
              metadata: labels: labels
              spec: {
                containers: [{
                  name: context.name
                  image: parameter.image
                  ports: [{ containerPort: parameter.port, name: "http" }]
                  resources: parameter.resources

                  readinessProbe: {
                    httpGet: { path: parameter.probePath, port: parameter.port }
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    failureThreshold: 3
                  }

                  livenessProbe: {
                    httpGet: { path: parameter.probePath, port: parameter.port }
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    failureThreshold: 3
                  }

                  if parameter.configMapName != _|_ {
                    envFrom: [{
                      configMapRef: { name: parameter.configMapName }
                    }]
                  }
                }]
              }
            }
          }
        }

        outputs: service: {
          apiVersion: "v1"
          kind: "Service"
          metadata: {
            name: context.name
            labels: labels
          }
          spec: {
            selector: labels
            ports: [{
              name: "http"
              port: parameter.port
              targetPort: parameter.port
            }]
          }
        }
