apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: https://kubevela.github.io/charts/
    chart: vela-core
    targetRevision: 1.10.6
    helm:
      values: |
        # defaults are fine for dev unless you need overrides
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
