apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela-addons
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  source:
    repoURL: https://github.com/adhatcher/kind-argocd-vela.git
    targetRevision: main
    path: gitops/clusters/zeus/infra/50-kubevela-addons
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true