apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: standard-topology
  namespace: vela-system
spec:
  appliesToWorkloads:
    - deployments.apps
  schematic:
    cue:
      template: |
        patch: {
          spec: template: spec: topologySpreadConstraints: [
            {
              maxSkew: 1
              topologyKey: "kubernetes.io/hostname"
              whenUnsatisfiable: "DoNotSchedule"
              labelSelector: matchLabels: {
                "app.oam.dev/component": context.name
              }
            },
            {
              maxSkew: 1
              topologyKey: "topology.kubernetes.io/zone"
              whenUnsatisfiable: "DoNotSchedule"
              labelSelector: matchLabels: {
                "app.oam.dev/component": context.name
              }
            },
          ]
        }
