apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: default-hpa
  namespace: vela-system
spec:
  appliesToWorkloads:
    - deployments.apps
  schematic:
    cue:
      template: |
        parameter: {
          disable: *false | bool
          minReplicas: *2 | int
          maxReplicas: *10 | int
          cpuUtilization: *70 | int
        }

        if parameter.disable == false {
          outputs: hpa: {
            apiVersion: "autoscaling/v2"
            kind: "HorizontalPodAutoscaler"
            metadata: {
              # keep deterministic; teams can disable + provide custom HPA with their own naming
              name: "\(context.name)-default"
              namespace: context.namespace
            }
            spec: {
              scaleTargetRef: {
                apiVersion: "apps/v1"
                kind: "Deployment"
                name: context.name
              }
              minReplicas: parameter.minReplicas
              maxReplicas: parameter.maxReplicas
              metrics: [{
                type: "Resource"
                resource: {
                  name: "cpu"
                  target: {
                    type: "Utilization"
                    averageUtilization: parameter.cpuUtilization
                  }
                }
              }]
            }
          }
        }
