apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: envoy-http-route
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        parameter: {
          host: string
          gatewayName: string
          gatewayNamespace: *"envoy-gateway-system" | string
          listenerSectionName: *"http" | string

          # defaults
          pathPrefix: *"/" | string
          port: *8080 | int
        }

        outputs: route: {
          apiVersion: "gateway.networking.k8s.io/v1"
          kind: "HTTPRoute"
          metadata: {
            name: context.name
            namespace: context.namespace
          }
          spec: {
            parentRefs: [{
              name: parameter.gatewayName
              namespace: parameter.gatewayNamespace
              sectionName: parameter.listenerSectionName
            }]
            hostnames: [parameter.host]
            rules: [{
              matches: [{
                path: {
                  type: "PathPrefix"
                  value: parameter.pathPrefix
                }
              }]
              backendRefs: [{
                name: context.name
                port: parameter.port
              }]
            }]
          }
        }
