apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: velaux-backend-tls
  namespace: vela-system
spec:
  targetRef:
    group: ""
    kind: Service
    name: kubevela-cluster-gateway-service
  tls:
    sni: vela.zeus
