apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: velaux
  namespace: vela-system
spec:
  parentRefs:
  - name: zeus-gw
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - vela.zeus
  rules:
  - backendRefs:
    - name: velaux
      port: 80